# Generated by Django 2.1.5 on 2019-02-21 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_message', models.CharField(max_length=500)),
                ('content_id', models.IntegerField()),
                ('object_pk', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderator_messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsNewsitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/img/new-img/')),
                ('body', models.TextField()),
                ('allow_comments', models.BooleanField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('preview', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_newsitem',
                'managed': True,
            },
        ),
    ]
