# Generated by Django 2.1.5 on 2019-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsnewsitem',
            name='allow_comments',
            field=models.BooleanField(verbose_name='Заборонити коментарi до новини'),
        ),
        migrations.AlterField(
            model_name='newsnewsitem',
            name='body',
            field=models.TextField(verbose_name='Текст новини'),
        ),
        migrations.AlterField(
            model_name='newsnewsitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/new-img/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='newsnewsitem',
            name='preview',
            field=models.TextField(verbose_name='Превью новини(те що буде видно на головнiй сторiнцi'),
        ),
        migrations.AlterField(
            model_name='newsnewsitem',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
