# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Good',
        ),
    ]
