# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinusstoreCommentnotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(unique=True)),
                ('user_id', models.IntegerField()),
                ('is_seen', models.IntegerField()),
                ('content_type_id', models.IntegerField()),
                ('object_id', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_commentnotify',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreFiletype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15)),
                ('display_name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filetype', models.CharField(max_length=30)),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_filetype',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minus',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinusauthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=255)),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minusauthor',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinusauthorFiletypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minusauthor_id', models.IntegerField()),
                ('filetype_id', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minusauthor_filetypes',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinuscategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=15)),
                ('display_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minuscategory',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinusplusrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('user_id', models.IntegerField()),
                ('file', models.CharField(max_length=2048)),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minusplusrecord',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinusrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('file', models.CharField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(max_length=255)),
                ('is_folk', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('arrangeuathor', models.CharField(blank=True, max_length=50, null=True)),
                ('annotation', models.TextField()),
                ('thematics', models.CharField(blank=True, max_length=30, null=True)),
                ('tempo', models.CharField(max_length=10)),
                ('staff', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('is_childish', models.IntegerField()),
                ('is_amateur', models.IntegerField()),
                ('is_ritual', models.IntegerField()),
                ('lyrics', models.TextField()),
                ('plusrecord', models.CharField(blank=True, max_length=2048, null=True)),
                ('pub_date', models.DateTimeField()),
                ('length', models.TimeField()),
                ('bitrate', models.IntegerField()),
                ('filesize', models.IntegerField()),
                ('embed_video', models.TextField(blank=True, null=True)),
                ('type_id', models.IntegerField()),
                ('rating_votes', models.IntegerField()),
                ('rating_score', models.IntegerField()),
                ('alternative', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minusrecord',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinusrecordCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minusrecord_id', models.IntegerField()),
                ('minuscategory_id', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minusrecord_categories',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinusstats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.IntegerField()),
                ('minus_id', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minusstats',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinusstopword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('blocked', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minusstopword',
            },
        ),
        migrations.CreateModel(
            name='MinusstoreMinusweekstats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('minus_id', models.IntegerField()),
            ],
            options={
                'managed': True,
                'db_table': 'minusstore_minusweekstats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='minusstoreminusrecordcategories',
            unique_together=set([('minusrecord_id', 'minuscategory_id')]),
        ),
    ]
